@startuml
class br.com.ajf.game.math.library.point2.Point2i {
+ <<Create>> Point2i()
+ <<Create>> Point2i(int,int)
+ <<Create>> Point2i(Point2<Integer>)
+ void set(Integer,Integer)
+ void set(IPoint2<Integer>)
+ void clampMin(Integer)
+ void clampMax(Integer)
+ void clamp(Integer,Integer)
+ void clamp(Integer,Integer,IPoint2<Integer>)
+ void clampMin(Integer,IPoint2<Integer>)
+ void clampMax(Integer,IPoint2<Integer>)
+ void absolute(IPoint2<Integer>)
+ void absolute()
+ void negate()
+ void negate(IPoint2<Integer>)
+ void add(IPoint2<Integer>)
+ void add(IPoint2<Integer>,IPoint2<Integer>)
+ void add(Integer,Integer)
+ void sub(IPoint2<Integer>)
+ void sub(IPoint2<Integer>,IPoint2<Integer>)
+ void sub(Integer,Integer)
+ void multiply(IPoint2<Integer>)
+ void divide(IPoint2<Integer>)
+ void scale(Integer)
+ void scale(IPoint2<Integer>,Integer)
+ void scaleAndAdd(IPoint2<Integer>,Integer)
+ void scaleAndAdd(IPoint2<Integer>,IPoint2<Integer>,Integer)
}

class br.com.ajf.game.math.library.matrix3.Matrix3d {
+ <<Create>> Matrix3d()
+ <<Create>> Matrix3d(Double,Double,Double,Double,Double,Double,Double,Double,Double)
+ <<Create>> Matrix3d(IMatrix3<Double>)
+ <<Create>> Matrix3d(Matrix3f)
+ <<Create>> Matrix3d(Double[][])
+ {static} void compute_svd(double[],double[],double[])
+ {static} int compute_qr(double[],double[],double[],double[])
~ {static} int compute_2X2(double,double,double,double[],double[],double[],double[],double[],int)
~ {static} double compute_rot(double,double,double[],double[],int,int)
~ {static} void mat_mul(double[],double[],double[])
~ {static} void transpose_mat(double[],double[])
~ {static} double max3(double[])
- {static} boolean almostEqual(double,double)
+ IMatrix3<Double> clone()
~ {static} void print_mat(double[])
~ {static} void print_det(double[])
~ {static} double max(double,double)
~ {static} double min(double,double)
~ {static} double d_sign(double,double)
~ {static} double compute_shift(double,double,double)
+ {static} void svdReorder(double[],double[],double[],double[],double[],double[])
+ void setIdentity()
+ void setScale(Double)
+ void setElement(int,int,Double)
+ void getRow(int,IPoint3<Double>)
+ void getRow(int,Double[])
+ void getColumn(int,IPoint3<Double>)
+ void getColumn(int,Double[])
+ Double getElement(int,int)
+ void setRow(int,Double,Double,Double)
+ void setRow(int,IPoint3<Double>)
+ void setRow(int,Double[])
+ void setColumn(int,Double,Double,Double)
+ void setColumn(int,IPoint3<Double>)
+ void setColumn(int,Double[])
+ Double getScale()
+ void add(Double)
+ void add(Double,IMatrix3<Double>)
+ void add(IMatrix3<Double>,IMatrix3<Double>)
+ void add(IMatrix3<Double>)
+ void sub(IMatrix3<Double>,IMatrix3<Double>)
+ void sub(IMatrix3<Double>)
+ void transpose()
+ void transpose(IMatrix3<Double>)
+ void set(Double[][])
+ void set(IMatrix3<Double>)
+ void set(Matrix3f)
+ {static} boolean luDecomposition(double[],int[])
+ {static} void luBackSubstitution(double[],int[],double[])
+ void invert()
+ void invert(IMatrix3<Double>)
+ void invertGeneral(IMatrix3<Double>)
+ Double determinate()
+ void set(Double)
+ void rotX(Double)
+ void rotY(Double)
+ void rotZ(Double)
+ void mul(Double)
+ void mul(Double,IMatrix3<Double>)
+ void mul(IMatrix3<Double>)
+ void mul(IMatrix3<Double>,IMatrix3<Double>)
+ void mulAndNormalize(IMatrix3<Double>,IMatrix3<Double>)
+ void mulAndNormalize(IMatrix3<Double>)
+ void mulAndTransposeBoth(IMatrix3<Double>,IMatrix3<Double>)
+ void mulAndTransposeRight(IMatrix3<Double>,IMatrix3<Double>)
+ void mulAndTransposeLeft(IMatrix3<Double>,IMatrix3<Double>)
+ void normalize()
+ void normalizeCP()
+ void normalize(IMatrix3<Double>)
+ void normalizeCP(IMatrix3<Double>)
+ boolean equals(IMatrix3<Double>)
+ boolean equals(Object)
+ int hashCode()
+ boolean epsilonEquals(IMatrix3<Double>,Double)
+ void setZero()
+ void negate()
+ void negate(IMatrix3<Double>)
+ void transform(IPoint3<Double>)
+ void getScaledRotate(double[],double[])
+ void set(AxisAngle4<Double>)
+ void set(Quat4f)
+ void set(Quat4d)
}

class br.com.ajf.game.math.library.point4.Point4f {
+ <<Create>> Point4f()
+ <<Create>> Point4f(float,float,float,float)
+ <<Create>> Point4f(float[])
+ <<Create>> Point4f(IPoint4<Float>)
+ void set(IPoint3<Float>)
+ float distanceSquared(IPoint4<Float>)
+ float distance(IPoint4<Float>)
+ float distanceL1(IPoint4<Float>)
+ float distanceLinF(IPoint4<Float>)
+ void project(IPoint4<Float>)
+ void set(float[])
+ float[] get()
+ void set(Float,Float,Float,Float)
+ void set(IPoint4<Float>)
+ void add(IPoint4<Float>)
+ void add(IPoint4<Float>,IPoint4<Float>)
+ void sub(IPoint4<Float>)
+ void sub(IPoint4<Float>,IPoint4<Float>)
+ void interpolate(IPoint4<Float>,float)
+ void interpolate(IPoint4<Float>,IPoint4<Float>,float)
+ boolean epsilonEquals(IPoint4<Float>,float)
+ void negate()
+ void negate(IPoint4<Float>)
+ void scale(Float)
+ void scale(Float,IPoint4<Float>)
+ void scaleAndAdd(Float,IPoint4<Float>)
+ void scaleAndAdd(Float,IPoint4<Float>,IPoint4<Float>)
+ void clamp(Float,Float,IPoint4<Float>)
+ void clampMin(Float,IPoint4<Float>)
+ void clampMax(Float,IPoint4<Float>)
+ void absolute()
+ void absolute(IPoint4<Float>)
+ void clamp(Float,Float)
+ void clampMin(Float)
+ void clampMax(Float)
}

class br.com.ajf.game.math.library.quat4.Quat4f {
+ <<Create>> Quat4f()
+ <<Create>> Quat4f(float,float,float,float)
+ <<Create>> Quat4f(float[])
+ <<Create>> Quat4f(IPoint4<Float>)
+ <<Create>> Quat4f(Quat4f)
+ <<Create>> Quat4f(Quat4d)
+ void conjugate(Quat4f)
+ void conjugate()
+ void mul(Quat4f,Quat4f)
+ void mul(Quat4f)
+ void mulInverse(Quat4f,Quat4f)
+ void mulInverse(Quat4f)
+ void inverse(Quat4f)
+ void inverse()
+ void normalize(Quat4f)
+ void normalize()
+ void set(Matrix3f)
+ void set(Matrix3d)
+ void set(AxisAngle4f)
+ void set(AxisAngle4d)
+ void interpolate(Quat4f,float)
+ void interpolate(Quat4f,Quat4f,float)
}

interface br.com.ajf.game.math.library.tuples.ITuple4 {
~ void get(X[])
~ void get(ITuple4<X>)
~ void set(X[])
~ void set(ITuple4<X>)
~ boolean equals(ITuple4<X>)
~ X r()
~ void setR(X)
~ X g()
~ void setG(X)
~ X b()
~ void setB(X)
~ X a()
~ void setA(X)
}

class br.com.ajf.game.math.library.point3.Point3d {
+ <<Create>> Point3d()
+ <<Create>> Point3d(double,double,double)
+ <<Create>> Point3d(double[])
+ <<Create>> Point3d(IPoint3<Double>)
+ void set(Double,Double,Double)
+ void set(IPoint3<Double>)
+ void set(double[])
+ void add(IPoint3<Double>)
+ void add(IPoint3<Double>,IPoint3<Double>)
+ void sub(IPoint3<Double>)
+ void sub(IPoint3<Double>,IPoint3<Double>)
+ void negate()
+ void negate(IPoint3<Double>)
+ void scale(Double)
+ void scale(Double,IPoint3<Double>)
+ void scaleAndAdd(Double,IPoint3<Double>,IPoint3<Double>)
+ void scaleAndAdd(Double,IPoint3<Double>)
+ void clamp(Double,Double,IPoint3<Double>)
+ void clampMin(Double,IPoint3<Double>)
+ void clampMax(Double,IPoint3<Double>)
+ void absolute()
+ void absolute(IPoint3<Double>)
+ void clamp(Double,Double)
+ double distanceSquared(IPoint3<Double>)
+ double distance(IPoint3<Double>)
+ double distanceL1(IPoint3<Double>)
+ double distanceLinF(IPoint3<Double>)
+ void project(IPoint4<Double>)
+ void interpolate(IPoint3<Double>,IPoint3<Double>,double)
+ void interpolate(IPoint3<Double>,double)
+ boolean epsilonEquals(IPoint3<Double>,double)
+ void clampMin(Double)
+ void clampMax(Double)
}

class br.com.ajf.game.math.library.point4.Point4i {
+ <<Create>> Point4i()
+ <<Create>> Point4i(int,int,int,int)
+ <<Create>> Point4i(int[])
+ <<Create>> Point4i(Point4<Integer>)
+ void set(int[])
+ int[] get()
+ void set(Integer,Integer,Integer,Integer)
+ void set(IPoint4<Integer>)
+ void add(IPoint4<Integer>)
+ void add(IPoint4<Integer>,IPoint4<Integer>)
+ void sub(IPoint4<Integer>)
+ void sub(IPoint4<Integer>,IPoint4<Integer>)
+ void negate()
+ void negate(IPoint4<Integer>)
+ void scale(Integer)
+ void scale(Integer,IPoint4<Integer>)
+ void scaleAndAdd(Integer,IPoint4<Integer>)
+ void scaleAndAdd(Integer,IPoint4<Integer>,IPoint4<Integer>)
+ void clamp(Integer,Integer,IPoint4<Integer>)
+ void clampMin(Integer,IPoint4<Integer>)
+ void clampMax(Integer,IPoint4<Integer>)
+ void absolute()
+ void absolute(IPoint4<Integer>)
+ void clamp(Integer,Integer)
+ void clampMin(Integer)
+ void clampMax(Integer)
}

class br.com.ajf.game.math.library.tuples.Tuple4 {
- X[] data
+ <<Create>> Tuple4()
+ <<Create>> Tuple4(X,X,X,X)
+ <<Create>> Tuple4(X[])
+ <<Create>> Tuple4(ITuple4<X>)
+ void get(X[])
+ void get(ITuple4<X>)
+ void set(X[])
+ void set(ITuple4<X>)
+ boolean equals(ITuple4<X>)
+ ITuple4<X> clone()
+ boolean equals(Object)
+ int hashCode()
+ String toString()
+ X r()
+ void setR(X)
+ X g()
+ void setG(X)
+ X b()
+ void setB(X)
+ X a()
+ void setA(X)
}


class br.com.ajf.game.math.library.tex.TexCoord4f {
+ <<Create>> TexCoord4f()
+ <<Create>> TexCoord4f(float,float,float,float)
+ <<Create>> TexCoord4f(float[])
+ <<Create>> TexCoord4f(TexCoord4f)
+ <<Create>> TexCoord4f(IPoint4<Float>)
}

class br.com.ajf.game.math.library.colors.Color3f {
+ <<Create>> Color3f()
+ <<Create>> Color3f(Float,Float,Float)
+ <<Create>> Color3f(ITuple3<Float>)
+ <<Create>> Color3f(Color)
+ <<Create>> Color3f(Color3f)
+ <<Create>> Color3f(Float[])
+ void set(Color)
+ Color get()
}

interface br.com.ajf.game.math.library.tuples.ITuple2 {
~ void set(X,X)
~ void set(X[])
~ void set(ITuple2<X>)
~ void get(X[])
~ void get(ITuple2<X>)
~ boolean equals(ITuple2<X>)
~ X x()
~ void setX(X)
~ X y()
~ void setY(X)
}

class br.com.ajf.game.math.library.axisangle4.AxisAngle4f {
+ <<Create>> AxisAngle4f()
+ <<Create>> AxisAngle4f(Float,Float,Float,Float)
+ <<Create>> AxisAngle4f(Float[])
+ <<Create>> AxisAngle4f(AxisAngle4<Float>)
+ <<Create>> AxisAngle4f(IPoint3<Float>,Float)
+ void set(Float,Float,Float,Float)
+ void set(Float[])
+ void set(AxisAngle4<Float>)
+ void set(IPoint3<Float>,Float)
+ void get(Float[])
+ void set(Quat4f)
+ void set(Quat4d)
+ void set(Matrix3f)
+ void set(Matrix3d)
+ boolean epsilonEquals(AxisAngle4<Float>,Float)
}

class br.com.ajf.game.math.library.point2.Point2f {
+ <<Create>> Point2f()
+ <<Create>> Point2f(float,float)
+ <<Create>> Point2f(IPoint2<Float>)
+ float distanceSquared(IPoint2<Float>)
+ float distance(IPoint2<Float>)
+ float distanceL1(IPoint2<Float>)
+ float distanceLinF(IPoint2<Float>)
+ void set(Float,Float)
+ void set(IPoint2<Float>)
+ void clampMin(Float)
+ void clampMax(Float)
+ void clamp(Float,Float)
+ void clamp(Float,Float,IPoint2<Float>)
+ void clampMin(Float,IPoint2<Float>)
+ void clampMax(Float,IPoint2<Float>)
+ void absolute(IPoint2<Float>)
+ void absolute()
+ void negate()
+ void negate(IPoint2<Float>)
+ void add(IPoint2<Float>)
+ void add(IPoint2<Float>,IPoint2<Float>)
+ void add(Float,Float)
+ void sub(IPoint2<Float>)
+ void sub(IPoint2<Float>,IPoint2<Float>)
+ void sub(Float,Float)
+ void multiply(IPoint2<Float>)
+ void interpolate(IPoint2<Float>,Float)
+ void interpolate(IPoint2<Float>,IPoint2<Float>,Float)
+ boolean epsilonEquals(IPoint2<Float>,Float)
+ void divide(IPoint2<Float>)
+ void scale(Float)
+ void scale(IPoint2<Float>,Float)
+ void scaleAndAdd(IPoint2<Float>,Float)
+ void scaleAndAdd(IPoint2<Float>,IPoint2<Float>,Float)
}

interface br.com.ajf.game.math.library.point4.IPoint4 {
~ X x()
~ void setX(X)
~ X y()
~ void setY(X)
~ X z()
~ void setZ(X)
~ X w()
~ void setW(X)
~ boolean equals(IPoint4<X>)
~ void set(X,X,X,X)
~ void set(IPoint4<X>)
~ void add(IPoint4<X>)
~ void add(IPoint4<X>,IPoint4<X>)
~ void sub(IPoint4<X>)
~ void sub(IPoint4<X>,IPoint4<X>)
~ void negate()
~ void negate(IPoint4<X>)
~ void scale(X)
~ void scale(X,IPoint4<X>)
~ void scaleAndAdd(X,IPoint4<X>)
~ void scaleAndAdd(X,IPoint4<X>,IPoint4<X>)
~ void clamp(X,X,IPoint4<X>)
~ void clampMin(X,IPoint4<X>)
~ void clampMax(X,IPoint4<X>)
~ void absolute()
~ void absolute(IPoint4<X>)
~ void clamp(X,X)
~ void clampMin(X)
~ void clampMax(X)
}

class br.com.ajf.game.math.library.tex.TexCoord3f {
+ <<Create>> TexCoord3f()
+ <<Create>> TexCoord3f(float,float,float)
+ <<Create>> TexCoord3f(float[])
+ <<Create>> TexCoord3f(TexCoord3f)
+ <<Create>> TexCoord3f(IPoint3<Float>)
}

class br.com.ajf.game.math.library.vector4.Vector4f {
+ <<Create>> Vector4f()
+ <<Create>> Vector4f(float,float,float,float)
+ <<Create>> Vector4f(float[])
+ <<Create>> Vector4f(IPoint4<Float>)
+ <<Create>> Vector4f(Vector4f)
+ void normalize(Vector4f)
+ void normalize()
+ Float angle(Vector4f)
+ Float dot(Vector4f)
+ Float length()
+ Float lengthSquared()
}

abstract class br.com.ajf.game.math.library.point4.Point4 {
- X[] x
+ <<Create>> Point4()
+ <<Create>> Point4(X,X,X,X)
+ <<Create>> Point4(IPoint4<X>)
+ boolean equals(IPoint4<X>)
+ boolean equals(Object)
+ int hashCode()
+ IPoint4<X> clone()
+ String toString()
+ X x()
+ void setX(X)
+ X y()
+ void setY(X)
+ X z()
+ void setZ(X)
+ X w()
+ void setW(X)
}


class br.com.ajf.game.math.library.vector3.Vector3f {
+ <<Create>> Vector3f()
+ <<Create>> Vector3f(float,float,float)
+ <<Create>> Vector3f(float[])
+ <<Create>> Vector3f(IPoint3<Float>)
+ <<Create>> Vector3f(Vector3f)
+ void normalize(Vector3f)
+ void normalize()
+ Float angle(Vector3f)
+ Float lengthSquared()
+ Float length()
+ void cross(Vector3f,Vector3f)
+ Float dot(Vector3f)
}

abstract class br.com.ajf.game.math.library.matrix3.Matrix3 {
- X[][] matrix
+ <<Create>> Matrix3()
+ <<Create>> Matrix3(X,X,X,X,X,X,X,X,X)
+ <<Create>> Matrix3(IMatrix3<X>)
+ <<Create>> Matrix3(X[][])
+ X[][] getMatrix()
+ void setMatrix(X[][])
+ void set(X,X,X,X,X,X,X,X,X)
+ IMatrix3<X> clone()
+ boolean equals(IMatrix3<X>)
+ X getM00()
+ void setM00(X)
+ X getM01()
+ void setM01(X)
+ X getM02()
+ void setM02(X)
+ X getM10()
+ void setM10(X)
+ X getM11()
+ void setM11(X)
+ X getM12()
+ void setM12(X)
+ X getM20()
+ void setM20(X)
+ X getM21()
+ void setM21(X)
+ X getM22()
+ void setM22(X)
+ boolean equals(Object)
+ int hashCode()
+ String toString()
}


class br.com.ajf.game.math.library.colors.Color3b {
+ <<Create>> Color3b()
+ <<Create>> Color3b(Byte,Byte,Byte)
+ <<Create>> Color3b(ITuple3<Byte>)
+ <<Create>> Color3b(Color)
+ <<Create>> Color3b(Color3b)
+ <<Create>> Color3b(Byte[])
+ void set(Color)
+ Color get()
}

abstract class br.com.ajf.game.math.library.tuples.Tuple2 {
- X[] data
+ void set(X,X)
+ void set(X[])
+ void set(ITuple2<X>)
+ void get(X[])
+ void get(ITuple2<X>)
+ boolean equals(ITuple2<X>)
+ boolean equals(Object)
+ ITuple2<X> clone()
+ int hashCode()
+ String toString()
+ X x()
+ void setX(X)
+ X y()
+ void setY(X)
}


interface br.com.ajf.game.math.library.point3.IPoint3 {
~ X x()
~ void setX(X)
~ X y()
~ void setY(X)
~ X z()
~ void setZ(X)
~ void set(X,X,X)
~ void set(IPoint3<X>)
~ void add(IPoint3<X>)
~ void add(IPoint3<X>,IPoint3<X>)
~ void sub(IPoint3<X>)
~ void sub(IPoint3<X>,IPoint3<X>)
~ void negate()
~ void negate(IPoint3<X>)
~ void scale(X)
~ void scale(X,IPoint3<X>)
~ void scaleAndAdd(X,IPoint3<X>,IPoint3<X>)
~ void scaleAndAdd(X,IPoint3<X>)
~ void clamp(X,X,IPoint3<X>)
~ void clampMin(X,IPoint3<X>)
~ void clampMax(X,IPoint3<X>)
~ void absolute()
~ void absolute(IPoint3<X>)
~ void clamp(X,X)
~ void clampMin(X)
~ void clampMax(X)
}

class br.com.ajf.game.math.library.point3.Point3f {
+ <<Create>> Point3f()
+ <<Create>> Point3f(float,float,float)
+ <<Create>> Point3f(float[])
+ <<Create>> Point3f(IPoint3<Float>)
+ void set(Float,Float,Float)
+ void set(IPoint3<Float>)
+ void set(float[])
+ void add(IPoint3<Float>)
+ void add(IPoint3<Float>,IPoint3<Float>)
+ void sub(IPoint3<Float>)
+ void sub(IPoint3<Float>,IPoint3<Float>)
+ void negate()
+ void negate(IPoint3<Float>)
+ void scale(Float)
+ void scale(Float,IPoint3<Float>)
+ void scaleAndAdd(Float,IPoint3<Float>,IPoint3<Float>)
+ void scaleAndAdd(Float,IPoint3<Float>)
+ void clamp(Float,Float,IPoint3<Float>)
+ void clampMin(Float,IPoint3<Float>)
+ void clampMax(Float,IPoint3<Float>)
+ void absolute()
+ void absolute(IPoint3<Float>)
+ void clamp(Float,Float)
+ float distanceSquared(IPoint3<Float>)
+ float distance(IPoint3<Float>)
+ float distanceL1(IPoint3<Float>)
+ float distanceLinF(IPoint3<Float>)
+ void project(IPoint4<Float>)
+ void interpolate(IPoint3<Float>,IPoint3<Float>,float)
+ void interpolate(IPoint3<Float>,float)
+ boolean epsilonEquals(IPoint3<Float>,float)
+ void clampMin(Float)
+ void clampMax(Float)
}

class br.com.ajf.game.math.library.colors.Color4f {
+ <<Create>> Color4f()
+ <<Create>> Color4f(Float,Float,Float,Float)
+ <<Create>> Color4f(Float[])
+ <<Create>> Color4f(Color4f)
+ <<Create>> Color4f(ITuple4<Float>)
+ <<Create>> Color4f(Color)
+ void set(Color)
+ Color get()
}

abstract class br.com.ajf.game.math.library.axisangle4.AxisAngle4 {
- X[] data
+ <<Create>> AxisAngle4()
+ <<Create>> AxisAngle4(X,X,X,X)
+ <<Create>> AxisAngle4(X[])
+ <<Create>> AxisAngle4(AxisAngle4<X>)
+ <<Create>> AxisAngle4(IPoint3<X>,X)
+ {abstract}void set(X,X,X,X)
+ {abstract}void set(X[])
+ {abstract}void set(AxisAngle4<X>)
+ {abstract}void set(IPoint3<X>,X)
+ {abstract}void get(X[])
+ {abstract}void set(Quat4f)
+ {abstract}void set(Quat4d)
+ {abstract}void set(Matrix3f)
+ {abstract}void set(Matrix3d)
+ {abstract}boolean epsilonEquals(AxisAngle4<X>,X)
+ X x()
+ void setX(X)
+ X y()
+ void setY(X)
+ X z()
+ void setZ(X)
+ X angle()
+ void setAngle(X)
+ String toString()
+ boolean equals(AxisAngle4<X>)
+ boolean equals(Object)
+ int hashCode()
+ AxisAngle4<X> clone()
}


interface br.com.ajf.game.math.library.tuples.ITuple3 {
~ void get(X[])
~ void get(ITuple3<X>)
~ void set(X[])
~ void set(ITuple3<X>)
~ boolean equals(ITuple3<X>)
~ X r()
~ void setR(X)
~ X g()
~ void setG(X)
~ X b()
~ void setB(X)
}

abstract class br.com.ajf.game.math.library.point2.Point2 {
- X[] x
+ <<Create>> Point2()
+ <<Create>> Point2(X,X)
+ <<Create>> Point2(IPoint2<X>)
+ X x()
+ void setX(X)
+ X y()
+ void setY(X)
+ String toString()
+ boolean equals(Object)
+ boolean equals(IPoint2<X>)
+ int hashCode()
+ IPoint2<X> clone()
}


interface br.com.ajf.game.math.library.point2.IPoint2 {
~ X x()
~ void setX(X)
~ X y()
~ void setY(X)
~ void set(X,X)
~ void set(IPoint2<X>)
~ void clampMin(X)
~ void clampMax(X)
~ void clamp(X,X)
~ void clamp(X,X,IPoint2<X>)
~ void clampMin(X,IPoint2<X>)
~ void clampMax(X,IPoint2<X>)
~ void absolute(IPoint2<X>)
~ void absolute()
~ void negate()
~ void negate(IPoint2<X>)
~ void add(IPoint2<X>)
~ void add(IPoint2<X>,IPoint2<X>)
~ void add(X,X)
~ void sub(IPoint2<X>)
~ void sub(IPoint2<X>,IPoint2<X>)
~ void sub(X,X)
~ void multiply(IPoint2<X>)
~ void divide(IPoint2<X>)
~ void scale(X)
~ void scale(IPoint2<X>,X)
~ void scaleAndAdd(IPoint2<X>,X)
~ void scaleAndAdd(IPoint2<X>,IPoint2<X>,X)
~ boolean equals(IPoint2<X>)
}

class br.com.ajf.game.math.library.vector2.Vector2d {
+ <<Create>> Vector2d()
+ <<Create>> Vector2d(double,double)
+ <<Create>> Vector2d(Point2<Double>)
+ <<Create>> Vector2d(double[])
+ <<Create>> Vector2d(Vector2d)
+ Double lengthSquared()
+ void normalize()
+ Double angle(Vector2d)
+ void normalize(Vector2d)
+ Double dot(Vector2d)
+ Double length()
}

class br.com.ajf.game.math.library.vector3.Vector3d {
+ <<Create>> Vector3d()
+ <<Create>> Vector3d(double,double,double)
+ <<Create>> Vector3d(double[])
+ <<Create>> Vector3d(IPoint3<Double>)
+ <<Create>> Vector3d(Vector3d)
+ void normalize(Vector3d)
+ void normalize()
+ Double angle(Vector3d)
+ Double lengthSquared()
+ Double length()
+ void cross(Vector3d,Vector3d)
+ Double dot(Vector3d)
}

class br.com.ajf.game.math.library.vector4.Vector4d {
+ <<Create>> Vector4d()
+ <<Create>> Vector4d(double,double,double,double)
+ <<Create>> Vector4d(double[])
+ <<Create>> Vector4d(IPoint4<Double>)
+ <<Create>> Vector4d(Vector4d)
+ void normalize(Vector4d)
+ void normalize()
+ Double angle(Vector4d)
+ Double dot(Vector4d)
+ Double length()
+ Double lengthSquared()
}

class br.com.ajf.game.math.library.point4.Point4d {
+ <<Create>> Point4d()
+ <<Create>> Point4d(double,double,double,double)
+ <<Create>> Point4d(double[])
+ <<Create>> Point4d(IPoint4<Double>)
+ void set(IPoint3<Double>)
+ double distanceSquared(IPoint4<Double>)
+ double distance(IPoint4<Double>)
+ double distanceL1(IPoint4<Double>)
+ double distanceLinF(IPoint4<Double>)
+ void project(IPoint4<Double>)
+ void set(double[])
+ double[] get()
+ void set(Double,Double,Double,Double)
+ void set(IPoint4<Double>)
+ void add(IPoint4<Double>)
+ void add(IPoint4<Double>,IPoint4<Double>)
+ void sub(IPoint4<Double>)
+ void sub(IPoint4<Double>,IPoint4<Double>)
+ void interpolate(IPoint4<Double>,double)
+ void interpolate(IPoint4<Double>,IPoint4<Double>,double)
+ boolean epsilonEquals(IPoint4<Double>,double)
+ void negate()
+ void negate(IPoint4<Double>)
+ void scale(Double)
+ void scale(Double,IPoint4<Double>)
+ void scaleAndAdd(Double,IPoint4<Double>)
+ void scaleAndAdd(Double,IPoint4<Double>,IPoint4<Double>)
+ void clamp(Double,Double,IPoint4<Double>)
+ void clampMin(Double,IPoint4<Double>)
+ void clampMax(Double,IPoint4<Double>)
+ void absolute()
+ void absolute(IPoint4<Double>)
+ void clamp(Double,Double)
+ void clampMin(Double)
+ void clampMax(Double)
}

class br.com.ajf.game.math.library.quat4.Quat4d {
+ <<Create>> Quat4d()
+ <<Create>> Quat4d(double,double,double,double)
+ <<Create>> Quat4d(double[])
+ <<Create>> Quat4d(IPoint4<Double>)
+ <<Create>> Quat4d(Quat4d)
+ <<Create>> Quat4d(Quat4f)
+ void conjugate(Quat4d)
+ void conjugate()
+ void mul(Quat4d,Quat4d)
+ void mul(Quat4d)
+ void mulInverse(Quat4d,Quat4d)
+ void mulInverse(Quat4d)
+ void inverse(Quat4d)
+ void inverse()
+ void normalize(Quat4f)
+ void normalize()
+ void set(Matrix3f)
+ void set(Matrix3d)
+ void set(AxisAngle4f)
+ void set(AxisAngle4d)
+ void interpolate(Quat4f,float)
+ void interpolate(Quat4f,Quat4f,float)
}

class br.com.ajf.game.math.library.point3.Point3i {
+ <<Create>> Point3i()
+ <<Create>> Point3i(int,int,int)
+ <<Create>> Point3i(int[])
+ <<Create>> Point3i(Point3<Integer>)
+ void set(Integer,Integer,Integer)
+ void set(IPoint3<Integer>)
+ void set(int[])
+ void add(IPoint3<Integer>)
+ void add(IPoint3<Integer>,IPoint3<Integer>)
+ void sub(IPoint3<Integer>)
+ void sub(IPoint3<Integer>,IPoint3<Integer>)
+ void negate()
+ void negate(IPoint3<Integer>)
+ void scale(Integer)
+ void scale(Integer,IPoint3<Integer>)
+ void scaleAndAdd(Integer,IPoint3<Integer>,IPoint3<Integer>)
+ void scaleAndAdd(Integer,IPoint3<Integer>)
+ void clamp(Integer,Integer,IPoint3<Integer>)
+ void clampMin(Integer,IPoint3<Integer>)
+ void clampMax(Integer,IPoint3<Integer>)
+ void absolute()
+ void absolute(IPoint3<Integer>)
+ void clamp(Integer,Integer)
+ void clampMin(Integer)
+ void clampMax(Integer)
}

class br.com.ajf.game.math.library.vector2.Vector2f {
+ <<Create>> Vector2f()
+ <<Create>> Vector2f(float,float)
+ <<Create>> Vector2f(IPoint2<Float>)
+ <<Create>> Vector2f(float[])
+ <<Create>> Vector2f(Vector2f)
+ Float lengthSquared()
+ void normalize()
+ Float angle(Vector2f)
+ void normalize(Vector2f)
+ Float dot(Vector2f)
+ Float length()
}

class br.com.ajf.game.math.library.axisangle4.AxisAngle4d {
+ <<Create>> AxisAngle4d()
+ <<Create>> AxisAngle4d(Double,Double,Double,Double)
+ <<Create>> AxisAngle4d(Double[])
+ <<Create>> AxisAngle4d(AxisAngle4<Double>)
+ <<Create>> AxisAngle4d(IPoint3<Double>,Double)
+ void set(Double,Double,Double,Double)
+ void set(Double[])
+ void set(AxisAngle4<Double>)
+ void set(IPoint3<Double>,Double)
+ void get(Double[])
+ void set(Quat4f)
+ void set(Quat4d)
+ void set(Matrix3f)
+ void set(Matrix3d)
+ boolean epsilonEquals(AxisAngle4<Double>,Double)
}

class br.com.ajf.game.math.library.colors.Color4b {
+ <<Create>> Color4b()
+ <<Create>> Color4b(Byte,Byte,Byte,Byte)
+ <<Create>> Color4b(Byte[])
+ <<Create>> Color4b(Color4b)
+ <<Create>> Color4b(ITuple4<Byte>)
+ <<Create>> Color4b(Color)
+ void set(Color)
+ Color get()
}

class br.com.ajf.game.math.library.point2.Point2d {
+ <<Create>> Point2d()
+ <<Create>> Point2d(double,double)
+ <<Create>> Point2d(IPoint2<Double>)
+ double distanceSquared(IPoint2<Double>)
+ double distance(IPoint2<Double>)
+ double distanceL1(IPoint2<Double>)
+ double distanceLinF(IPoint2<Double>)
+ void set(Double,Double)
+ void set(IPoint2<Double>)
+ void clampMin(Double)
+ void clampMax(Double)
+ void clamp(Double,Double)
+ void clamp(Double,Double,IPoint2<Double>)
+ void clampMin(Double,IPoint2<Double>)
+ void clampMax(Double,IPoint2<Double>)
+ void absolute(IPoint2<Double>)
+ void absolute()
+ void negate()
+ void negate(IPoint2<Double>)
+ void add(IPoint2<Double>)
+ void add(IPoint2<Double>,IPoint2<Double>)
+ void add(Double,Double)
+ void sub(IPoint2<Double>)
+ void sub(IPoint2<Double>,IPoint2<Double>)
+ void sub(Double,Double)
+ void multiply(IPoint2<Double>)
+ void interpolate(IPoint2<Double>,Double)
+ void interpolate(IPoint2<Double>,IPoint2<Double>,Double)
+ boolean epsilonEquals(IPoint2<Double>,Double)
+ void divide(IPoint2<Double>)
+ void scale(Double)
+ void scale(IPoint2<Double>,Double)
+ void scaleAndAdd(IPoint2<Double>,Double)
+ void scaleAndAdd(IPoint2<Double>,IPoint2<Double>,Double)
}

abstract class br.com.ajf.game.math.library.tuples.Tuple3 {
- X[] data
+ <<Create>> Tuple3()
+ <<Create>> Tuple3(X,X,X)
+ <<Create>> Tuple3(ITuple3<X>)
+ <<Create>> Tuple3(X[])
+ void get(X[])
+ void get(ITuple3<X>)
+ void set(X[])
+ void set(ITuple3<X>)
+ boolean equals(ITuple3<X>)
+ boolean equals(Object)
+ int hashCode()
+ String toString()
+ ITuple3<X> clone()
+ X r()
+ void setR(X)
+ X g()
+ void setG(X)
+ X b()
+ void setB(X)
}


class br.com.ajf.game.math.library.matrix3.Matrix3f {
+ <<Create>> Matrix3f()
+ <<Create>> Matrix3f(Float,Float,Float,Float,Float,Float,Float,Float,Float)
+ <<Create>> Matrix3f(IMatrix3<Float>)
+ <<Create>> Matrix3f(Matrix3d)
+ <<Create>> Matrix3f(Float[][])
+ void setIdentity()
+ void setScale(Float)
+ void setElement(int,int,Float)
+ void getRow(int,IPoint3<Float>)
+ void getRow(int,Float[])
+ void getColumn(int,IPoint3<Float>)
+ void getColumn(int,Float[])
+ Float getElement(int,int)
+ void setRow(int,Float,Float,Float)
+ void setRow(int,IPoint3<Float>)
+ void setRow(int,Float[])
+ void setColumn(int,Float,Float,Float)
+ void setColumn(int,IPoint3<Float>)
+ void setColumn(int,Float[])
+ Float getScale()
+ void add(Float)
+ void add(Float,IMatrix3<Float>)
+ void add(IMatrix3<Float>,IMatrix3<Float>)
+ void add(IMatrix3<Float>)
+ void sub(IMatrix3<Float>,IMatrix3<Float>)
+ void sub(IMatrix3<Float>)
+ void transpose()
+ void transpose(IMatrix3<Float>)
+ void set(Float[][])
+ void set(IMatrix3<Float>)
+ void set(Matrix3d)
+ {static} boolean luDecomposition(double[],int[])
+ {static} void luBackSubstitution(double[],int[],double[])
+ void invert()
+ void invert(IMatrix3<Float>)
+ void invertGeneral(IMatrix3<Float>)
+ Float determinate()
+ void set(Float)
+ void rotX(Float)
+ void rotY(Float)
+ void rotZ(Float)
+ void mul(Float)
+ void mul(Float,IMatrix3<Float>)
+ void mul(IMatrix3<Float>)
+ void mul(IMatrix3<Float>,IMatrix3<Float>)
+ void mulAndNormalize(IMatrix3<Float>,IMatrix3<Float>)
+ void mulAndNormalize(IMatrix3<Float>)
+ void mulAndTransposeBoth(IMatrix3<Float>,IMatrix3<Float>)
+ void mulAndTransposeRight(IMatrix3<Float>,IMatrix3<Float>)
+ void mulAndTransposeLeft(IMatrix3<Float>,IMatrix3<Float>)
+ void normalize()
+ void normalizeCP()
+ void normalize(IMatrix3<Float>)
+ void normalizeCP(IMatrix3<Float>)
+ boolean equals(IMatrix3<Float>)
+ boolean equals(Object)
+ int hashCode()
+ boolean epsilonEquals(IMatrix3<Float>,Float)
+ void setZero()
+ void negate()
+ void negate(IMatrix3<Float>)
+ void transform(IPoint3<Float>)
+ void getScaledRotate(double[],double[])
+ void set(AxisAngle4<Float>)
+ void set(Quat4f)
+ void set(Quat4d)
}

class br.com.ajf.game.math.library.tex.TexCoord2f {
+ <<Create>> TexCoord2f()
+ <<Create>> TexCoord2f(float,float)
+ <<Create>> TexCoord2f(float[])
+ <<Create>> TexCoord2f(IPoint2<Float>)
+ <<Create>> TexCoord2f(TexCoord2f)
}

interface br.com.ajf.game.math.library.matrix3.IMatrix3 {
~ X[][] getMatrix()
~ void setMatrix(X[][])
~ boolean equals(IMatrix3<X>)
~ X getM00()
~ void setM00(X)
~ X getM01()
~ void setM01(X)
~ X getM02()
~ void setM02(X)
~ X getM10()
~ void setM10(X)
~ X getM11()
~ void setM11(X)
~ X getM12()
~ void setM12(X)
~ X getM20()
~ void setM20(X)
~ X getM21()
~ void setM21(X)
~ X getM22()
~ void setM22(X)
~ void setIdentity()
~ void setScale(X)
~ void setElement(int,int,X)
~ void getRow(int,IPoint3<X>)
~ void getRow(int,X[])
~ void getColumn(int,IPoint3<X>)
~ void getColumn(int,X[])
~ X getElement(int,int)
~ void setRow(int,X,X,X)
~ void setRow(int,IPoint3<X>)
~ void setRow(int,X[])
~ void setColumn(int,X,X,X)
~ void setColumn(int,IPoint3<X>)
~ void setColumn(int,X[])
~ X getScale()
~ void add(X)
~ void add(X,IMatrix3<X>)
~ void add(IMatrix3<X>,IMatrix3<X>)
~ void add(IMatrix3<X>)
~ void sub(IMatrix3<X>,IMatrix3<X>)
~ void sub(IMatrix3<X>)
~ void transpose()
~ void transpose(IMatrix3<X>)
~ void set(X[][])
~ void set(IMatrix3<X>)
~ void invert()
~ void invert(IMatrix3<X>)
~ void invertGeneral(IMatrix3<X>)
~ X determinate()
~ void set(X)
~ void rotX(X)
~ void rotY(X)
~ void rotZ(X)
~ void mul(X)
~ void mul(X,IMatrix3<X>)
~ void mul(IMatrix3<X>)
~ void mul(IMatrix3<X>,IMatrix3<X>)
~ void mulAndNormalize(IMatrix3<X>,IMatrix3<X>)
~ void mulAndNormalize(IMatrix3<X>)
~ void mulAndTransposeBoth(IMatrix3<X>,IMatrix3<X>)
~ void mulAndTransposeRight(IMatrix3<X>,IMatrix3<X>)
~ void mulAndTransposeLeft(IMatrix3<X>,IMatrix3<X>)
~ void normalize()
~ void normalizeCP()
~ void normalize(IMatrix3<X>)
~ void normalizeCP(IMatrix3<X>)
~ boolean epsilonEquals(IMatrix3<X>,X)
~ void setZero()
~ void negate()
~ void negate(IMatrix3<X>)
~ void transform(IPoint3<X>)
~ void getScaledRotate(double[],double[])
~ void set(AxisAngle4<X>)
~ void set(Quat4f)
~ void set(Quat4d)
}

class br.com.ajf.game.math.library.test.Vector2fTest {
+ void testVector2fNotNullWhenCreatedCorrect()
+ void testVector2fValues()
}

abstract class br.com.ajf.game.math.library.point3.Point3 {
- X[] x
+ <<Create>> Point3()
+ <<Create>> Point3(X,X,X)
+ <<Create>> Point3(IPoint3<X>)
+ boolean equals(IPoint3<X>)
+ boolean equals(Object)
+ int hashCode()
+ IPoint3<X> clone()
+ String toString()
+ X x()
+ void setX(X)
+ X y()
+ void setY(X)
+ X z()
+ void setZ(X)
}




br.com.ajf.game.math.library.point2.Point2 <|-- br.com.ajf.game.math.library.point2.Point2i
br.com.ajf.game.math.library.matrix3.Matrix3 <|-- br.com.ajf.game.math.library.matrix3.Matrix3d
br.com.ajf.game.math.library.point4.Point4 <|-- br.com.ajf.game.math.library.point4.Point4f
br.com.ajf.game.math.library.point4.Point4f <|-- br.com.ajf.game.math.library.quat4.Quat4f
java.io.Serializable <|-- br.com.ajf.game.math.library.tuples.ITuple4
br.com.ajf.game.math.library.tuples.Cloneable <|-- br.com.ajf.game.math.library.tuples.ITuple4
br.com.ajf.game.math.library.point3.Point3 <|-- br.com.ajf.game.math.library.point3.Point3d
br.com.ajf.game.math.library.point4.Point4 <|-- br.com.ajf.game.math.library.point4.Point4i
br.com.ajf.game.math.library.tuples.ITuple4 <|.. br.com.ajf.game.math.library.tuples.Tuple4
br.com.ajf.game.math.library.point4.Point4f <|-- br.com.ajf.game.math.library.tex.TexCoord4f
br.com.ajf.game.math.library.tuples.Tuple3 <|-- br.com.ajf.game.math.library.colors.Color3f
java.io.Serializable <|-- br.com.ajf.game.math.library.tuples.ITuple2
br.com.ajf.game.math.library.tuples.Cloneable <|-- br.com.ajf.game.math.library.tuples.ITuple2
br.com.ajf.game.math.library.axisangle4.AxisAngle4 <|-- br.com.ajf.game.math.library.axisangle4.AxisAngle4f
br.com.ajf.game.math.library.point2.Point2 <|-- br.com.ajf.game.math.library.point2.Point2f
java.io.Serializable <|-- br.com.ajf.game.math.library.point4.IPoint4
br.com.ajf.game.math.library.point4.Cloneable <|-- br.com.ajf.game.math.library.point4.IPoint4
br.com.ajf.game.math.library.point3.Point3f <|-- br.com.ajf.game.math.library.tex.TexCoord3f
br.com.ajf.game.math.library.point4.Point4f <|-- br.com.ajf.game.math.library.vector4.Vector4f
br.com.ajf.game.math.library.point4.IPoint4 <|.. br.com.ajf.game.math.library.point4.Point4
br.com.ajf.game.math.library.point3.Point3f <|-- br.com.ajf.game.math.library.vector3.Vector3f
br.com.ajf.game.math.library.matrix3.IMatrix3 <|.. br.com.ajf.game.math.library.matrix3.Matrix3
br.com.ajf.game.math.library.tuples.Tuple3 <|-- br.com.ajf.game.math.library.colors.Color3b
br.com.ajf.game.math.library.tuples.ITuple2 <|.. br.com.ajf.game.math.library.tuples.Tuple2
java.io.Serializable <|-- br.com.ajf.game.math.library.point3.IPoint3
br.com.ajf.game.math.library.point3.Cloneable <|-- br.com.ajf.game.math.library.point3.IPoint3
br.com.ajf.game.math.library.point3.Point3 <|-- br.com.ajf.game.math.library.point3.Point3f
br.com.ajf.game.math.library.tuples.Tuple4 <|-- br.com.ajf.game.math.library.colors.Color4f
java.io.Serializable <|.. br.com.ajf.game.math.library.axisangle4.AxisAngle4
br.com.ajf.game.math.library.axisangle4.Cloneable <|.. br.com.ajf.game.math.library.axisangle4.AxisAngle4
java.io.Serializable <|-- br.com.ajf.game.math.library.tuples.ITuple3
br.com.ajf.game.math.library.tuples.Cloneable <|-- br.com.ajf.game.math.library.tuples.ITuple3
br.com.ajf.game.math.library.point2.IPoint2 <|.. br.com.ajf.game.math.library.point2.Point2
java.io.Serializable <|-- br.com.ajf.game.math.library.point2.IPoint2
br.com.ajf.game.math.library.point2.Cloneable <|-- br.com.ajf.game.math.library.point2.IPoint2
br.com.ajf.game.math.library.point2.Point2d <|-- br.com.ajf.game.math.library.vector2.Vector2d
br.com.ajf.game.math.library.point3.Point3d <|-- br.com.ajf.game.math.library.vector3.Vector3d
br.com.ajf.game.math.library.point4.Point4d <|-- br.com.ajf.game.math.library.vector4.Vector4d
br.com.ajf.game.math.library.point4.Point4 <|-- br.com.ajf.game.math.library.point4.Point4d
br.com.ajf.game.math.library.point4.Point4d <|-- br.com.ajf.game.math.library.quat4.Quat4d
br.com.ajf.game.math.library.point3.Point3 <|-- br.com.ajf.game.math.library.point3.Point3i
br.com.ajf.game.math.library.point2.Point2f <|-- br.com.ajf.game.math.library.vector2.Vector2f
br.com.ajf.game.math.library.axisangle4.AxisAngle4 <|-- br.com.ajf.game.math.library.axisangle4.AxisAngle4d
br.com.ajf.game.math.library.tuples.Tuple4 <|-- br.com.ajf.game.math.library.colors.Color4b
br.com.ajf.game.math.library.point2.Point2 <|-- br.com.ajf.game.math.library.point2.Point2d
br.com.ajf.game.math.library.tuples.ITuple3 <|.. br.com.ajf.game.math.library.tuples.Tuple3
br.com.ajf.game.math.library.matrix3.Matrix3 <|-- br.com.ajf.game.math.library.matrix3.Matrix3f
br.com.ajf.game.math.library.point2.Point2f <|-- br.com.ajf.game.math.library.tex.TexCoord2f
java.io.Serializable <|-- br.com.ajf.game.math.library.matrix3.IMatrix3
br.com.ajf.game.math.library.matrix3.Cloneable <|-- br.com.ajf.game.math.library.matrix3.IMatrix3
br.com.ajf.game.math.library.point3.IPoint3 <|.. br.com.ajf.game.math.library.point3.Point3
@enduml